### ISSUE TITLE
How to find all feasible solutions

### ISSUE THREAD

**Issue by Riroaki** [DavideCanton/DancingLinksX#1]
Hello, thx for your efficient codes, and I just wonder how I can get all feasible solutions without telling the algorithmX to stop?

**Comment by Riroaki** [comment]
I tried by using a set to record all appeared solutions and return True when the new solution exist in the set. But I couldn't get solution for a long time, and I doubt that didn't work...

**Comment by DavideCanton** [comment]
Hi! If the callback returns True, the algorithm will stop. You have to provide a callback that returns False explicitly, or that doesn't return anything at all.

**Comment by Riroaki** [comment]
> Hi! If the callback returns True, the algorithm will stop. You have to provide a callback that returns False explicitly, or that doesn't return anything at all.

Actually I mean how to return False after all solutions have been returned, will the algorithm produce solutions in a cycle repeatedly?
In that case I just capture solution every time it returns and quit when the new solution already has been captured...

**Comment by DavideCanton** [comment]
> > Hi! If the callback returns True, the algorithm will stop. You have to provide a callback that returns False explicitly, or that doesn't return anything at all.
> 
> Actually I mean how to return False after all solutions have been returned, will the algorithm produce solutions in a cycle repeatedly?
> In that case I just capture solution every time it returns and quit when the new solution already has been captured...

No, the algorithm will stop when all the solutions are produced. You can terminate it early by explicitly returning True. If you check the examples, there is how to count all the solutions, it requires that the algorithm terminates.

**Comment by Riroaki** [comment]
Oh, I tried the nqueens example and it terminated after all solutions are produced, just like you've said.
Thank you! I 'd probably check again my former codes🤔
